version: "2"
services:

  bot:
    image: meowbot_discord
    build:
      context: .
    command: python /usr/src/app/main.py
    volumes:
      - ./:/usr/src/app:ro
    tty: true
    stdin_open: true
    depends_on:
      - redis

  redis:
    image: redis:5-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
